### ISSUE TITLE
Icons offset from background

### ISSUE THREAD

**Issue by theckhd** [SecretFox/GadgetManager#1]
Updated to 0.4.2 and noticed that the gadgets aren't aligned to the background. Ive moved my interface around a bit, and my guess is they're statically offset from the bottom of the screen rather than the abilities bar?

Also there's an overlapping issue with EffectsUI and FreeHuD. GadgetManager should be a higher strata than just about anything else since it's a temporary effect, but that may be something that isn't easy to fix depending on how that's coded in flash.

![gadgetmanager_420_bug](https://user-images.githubusercontent.com/6124772/57183050-6a96af80-6e75-11e9-92a3-b3b1be58c563.PNG)

**Comment by MakeMods** [comment]
It seems that i decided to draw background from bottom to top,but gadgets from top to bottom.
Latest release should fix it(although i think position calculations are really crappy) along with the layering issue.
